 services:
   filebrowser:
     image: filebrowser/filebrowser
     container_name: filebrowser
     ports:
       - "37873:80"
     volumes:
       - /:/srv
       - ./docker_env/filebrowser/filebrowser.db:/database/filebrowser.db
       - ./docker_env/filebrowser/settings.json:/config/settings.json
     environment:
       - PUID=${UID:-1000} # Default to UID 1000 if not set
       - PGID=${GID:-1000} # Default to GID 1000 if not set
     restart: always

   portainer:
     image: portainer/portainer-ce:latest
     container_name: portainer
     ports:
       - "47874:9000"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - ./docker_env/portainer:/data
     restart: always

   redis:
     image: redis:6.2.6-alpine
     container_name: redis
     restart: on-failure
     environment:
       - TZ=
     volumes:
       - ./docker_env/redis/data:/data
       - ./docker_env/redis/redis.conf:/etc/redis/redis.conf
     ports: # PORTS
       - "59783:6379"
     sysctls: # set core
       - net.core.somaxconn=1024
     command: /bin/sh -c "echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf && redis-server /etc/redis/redis.conf --appendonly yes" # Specify configuration file and enable persistence



